In [ ]:
#1.3.1
import numpy as np

A = np.arange(64).reshape(8, 8)
for i in range (0, 7, 2):
  a = np.zeros(8)
  b = np.ones(4)
  a[::2] = b
  A[i] = a
  # a = np.ones(8)
  # b = np.zeros(4)
  # a[::2] = b
  A[i + 1] = np.flip(a)
print(A)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [ ]:
#1.3.2
import numpy as np

A = np.arange(25).reshape(5, 5)

for i in range (1, 5):
  A[i] = A[0]
print(A)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
#1.3.3
import numpy as np

A = np.random.random((3,3,3))
print(A)

[[[0.36120925 0.43993932 0.97778228]
  [0.66211888 0.74671363 0.18551443]
  [0.5902114  0.69244724 0.65230969]]

 [[0.61516497 0.80806354 0.19042088]
  [0.67617038 0.90930201 0.31192291]
  [0.63188104 0.48370044 0.04798787]]

 [[0.56869263 0.64523843 0.6523958 ]
  [0.87949785 0.02806429 0.88822162]
  [0.3366643  0.64288013 0.02800001]]]


In [ ]:
#1.3.4
import numpy as np

n = int(input())
m = int(input())

A = np.zeros((n, m))
for i in range(0, len(A[0])):
  A[0, i] = 1
  A[len(A)-1, i] = 1

for i in range(0, len(A)):
  A[i, 0] = 1
  A[i, len(A[0]) - 1] = 1
print(A)

5
10
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
#1.3.5
import numpy as np

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr)[::-1])

[8 7 6 5 4 3 2 1]


In [ ]:
#1.3.6
import numpy as np

n = int(input())
m = int(input())

A = np.random.random((n,m))
if len(A) == 0 or (len(A[0])) == 0:
  print("Матрица не существует!")
elif len(A) == (len(A[0])):
  print("Квадратная матрица\nРазмер: ", len(A)*(len(A[0])),"\nРазмерность: ", len(A), "x", (len(A[0])))
elif len(A) != (len(A[0])):
  print("Прямоугольная матрица\nРазмер: ", len(A)*(len(A[0])),"\nРазмерность: ", len(A), "x", (len(A[0])))

5
1
Прямоугольная матрица
Размер:  5 
Размерность:  5 x 1


In [ ]:
#2.3.1
import pandas as pd
import numpy as np

a = pd.Series([2, 4, 6, 8])
b = pd.Series([1, 3, 5, 7])

dist = np.sqrt(np.sum((a - b)**2))

print(dist)

2.0


In [ ]:
#2.3.2
import pandas as pd
import numpy as np

url = 'https://raw.githubusercontent.com/akmand/datasets/main/FMLPDA_Table4_3.csv'
dataframe = pd.read_csv(url)
print(dataframe.head())

   stream     slope elevation vegetation
0   False     steep      high  chapparal
1    True  moderate       low   riparian
2    True     steep    medium   riparian
3   False     steep    medium  chapparal
4   False      flat      high    conifer


In [ ]:
#2.3.3
import pandas as pd
import numpy as np

url = 'https://raw.githubusercontent.com/akmand/datasets/main/FMLPDA_Table4_3.csv'
dataframe = pd.read_csv(url)
print(dataframe)
print("\n")
#2.2.5
print(dataframe.head(2))
print("\n")
print(dataframe.tail(3))
print("\n")
print(dataframe.shape)
print("\n")
print(dataframe.describe())
print("\n")
#2.2.6
print(dataframe.iloc[2:4])
print("\n")
#2.2.7
print(dataframe[dataframe['slope'] == 'steep'].head())

   stream     slope elevation vegetation
0   False     steep      high  chapparal
1    True  moderate       low   riparian
2    True     steep    medium   riparian
3   False     steep    medium  chapparal
4   False      flat      high    conifer
5    True     steep   highest    conifer
6    True     steep      high  chapparal


   stream     slope elevation vegetation
0   False     steep      high  chapparal
1    True  moderate       low   riparian


   stream  slope elevation vegetation
4   False   flat      high    conifer
5    True  steep   highest    conifer
6    True  steep      high  chapparal


(7, 4)


       stream  slope elevation vegetation
count       7      7         7          7
unique      2      3         4          3
top      True  steep      high  chapparal
freq        4      5         3          3


   stream  slope elevation vegetation
2    True  steep    medium   riparian
3   False  steep    medium  chapparal


   stream  slope elevation vegetation
0   False  steep

In [ ]:
import pandas as pd
from sklearn import preprocessing

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)

min_max_scaler = preprocessing.MinMaxScaler()
dataframe['sepal_length_cm'] = min_max_scaler.fit_transform(dataframe[['sepal_length_cm']])

z_score_scaler = preprocessing.StandardScaler()
dataframe['sepal_width_cm'] = z_score_scaler.fit_transform(dataframe[['sepal_width_cm']])

print(dataframe['sepal_length_cm'], "\n")
print(dataframe['sepal_width_cm'])

0      0.222222
1      0.166667
2      0.111111
3      0.083333
4      0.194444
         ...   
145    0.666667
146    0.555556
147    0.611111
148    0.527778
149    0.444444
Name: sepal_length_cm, Length: 150, dtype: float64 

0      1.032057
1     -0.124958
2      0.337848
3      0.106445
4      1.263460
         ...   
145   -0.124958
146   -1.281972
147   -0.124958
148    0.800654
149   -0.124958
Name: sepal_width_cm, Length: 150, dtype: float64
